Add internationalization of the app
ivalkou/freeaps pull request #23
Opened 2021-04-11 13:53 UTC by avouspierre

Add internationalization for each text in the app of the version 0.1.12

Adding the french translation

2021-04-12 10:11 UTC, ivalkou requested changes
SwiftUI Text component supports localization by design. No need to use NSLocalizedString. The presence of `Localized.strings` file is enough.

2021-04-13 08:09 UTC, avouspierre commented
I changed to remove all NSLocalizedString with SwiftUI components in the last commit.

2021-04-13 08:24 UTC, ivalkou commented on FreeAPS/Sources/Modules/Bolus/BolusViewModel.swift
> +                }, receiveValue: { _ in })
What is the meaning of this change? It is equivalent, but it has become longer.

2021-04-13 08:25 UTC, mountrcg commented
in the EN Localization file under
/* Enact Bolus title */
is still a french term

2021-04-13 08:33 UTC, ivalkou requested changes

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/Bolus/View/BolusRootView.swift
> +                Section(header: Text("Recommandation")) {
Please leave keys in English.

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/Bolus/View/BolusRootView.swift
> +                            Text("Insulin recommanded")
Please leave keys in English.

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/Bolus/View/BolusRootView.swift
> +            .navigationTitle("Enact Bolus Titre")
Please leave keys in English.

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/Bolus/View/BolusRootView.swift
> +                                ) }
Did you run the build? It feels like no, because auto-formatting didn't work.

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/ManualTempBasal/View/ManualTempBasalRootView.swift
> +                    Picker(selection: $viewModel.durationIndex, label: Text(NSLocalizedString("Duration", comment: "Duration"))) {
NSLocalizedString is not needed

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/PreferencesEditor/View/PreferencesEditorRootView.swift
> +                    Picker(NSLocalizedString("Glucose units", comment: "Glucose units"), selection: $viewModel.unitsIndex) {
NSLocalizedString is not needed

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/TargetsEditor/View/TargetsEditorRootView.swift
> +                Section(header: Text(NSLocalizedString("Schedule", comment: "Schedule"))) {
NSLocalizedString is not needed

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/TargetsEditor/View/TargetsEditorRootView.swift
> +                        Text(NSLocalizedString("Save", comment: "Save"))
NSLocalizedString is not needed

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/TargetsEditor/View/TargetsEditorRootView.swift
> +            .navigationTitle(NSLocalizedString("Target Ranges", comment: "Target Ranges"))
NSLocalizedString is not needed

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/TargetsEditor/View/TargetsEditorRootView.swift
> +                        Text(NSLocalizedString("Low target", comment: "Low target")).frame(width: geometry.size.width / 3)
the same

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/TargetsEditor/View/TargetsEditorRootView.swift
> +                        Text(NSLocalizedString("High target", comment: "High target")).frame(width: geometry.size.width / 3)
the same

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/TargetsEditor/View/TargetsEditorRootView.swift
> +                        Text(NSLocalizedString("Time", comment: "Time")).frame(width: geometry.size.width / 3)
the same

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/TargetsEditor/View/TargetsEditorRootView.swift
> +                            Text(NSLocalizedString("starts at", comment: "starts at")).foregroundColor(.secondary)
the same

2021-04-13 08:33 UTC, ivalkou commented on FreeAPS/Sources/Modules/TargetsEditor/View/TargetsEditorRootView.swift
> +                return AnyView(Button(action: onAdd) { Text(NSLocalizedString("Add", comment: "Add")) })
the same

2021-04-13 08:36 UTC, ivalkou commented on FreeAPS/Sources/Modules/AutotuneConfig/View/AutotuneConfigRootView.swift
> +                    Toggle(NSLocalizedString("use Autotune", comment: "Use Autotune"), isOn: $viewModel.useAutotune)
NSLocalizedString is not needed

2021-04-13 09:03 UTC, avouspierre commented
Integration of all comments. I builded and tested the app in french and in english and all seems to be OK.

2021-04-13 10:00 UTC, ivalkou requested changes
Almost done. A couple of remarks

2021-04-13 10:00 UTC, ivalkou commented on FreeAPS/Sources/Modules/AutotuneConfig/View/AutotuneConfigRootView.swift
> +                    Toggle("use Autotune", isOn: $viewModel.useAutotune)
Capital letter (and in .strings)

2021-04-13 10:05 UTC, ivalkou commented
Recommandation -> Recommendation

2021-04-13 12:52 UTC, ivalkou requested changes
I still see this:

```
/* StringRecommendation */
"Recommendation" = "Recommandation";
```

in English strings.

2021-04-13 12:54 UTC, ivalkou commented
And why do we need the word title in the title?

```
/* Enact Bolus title */
"Enact Bolus Title" = "Enact Bolus Title";

/* Add Carbs Title */
"Add Carbs Title" = "Add Carbs Title";
```

2021-04-13 13:16 UTC, avouspierre commented
I noticed the same sentences but in different locations, in particular between a titre of a page and a button label. When it's simple like "save", I didn't duplicate.  Indeed, I think that the translation in some languages could be different between a button label and title. That could be also an issue for the length of the text in the page (shorter capability for a button for example).

2021-04-13 21:23 UTC, ivalkou commented
@avouspierre The keys may be different, and that is good, but I don't understand why the word "title" is needed in the value. Seems like a mistake.

2021-04-13 21:42 UTC, ivalkou commented
@avouspierre You've done a great work, I just want to make sure everything is neat. If you don't understand what I want to achieve, I can accept the pull request and finish it myself. Now it is a little premature to do localizations, as functions will be added. But you have made a good start.

2021-04-14 08:12 UTC, avouspierre commented
Don't worry @ivalkou : I understand your objectives, you need to master the code of the amazing project and for me, I just try to learn to code in swift and improve my TD1 life in same time 😄. 

For the "Title", I would like to differenciate : 
```
/* Enact Bolus */
"Enact bolus" = "Enact bolus"; <--- for the "action/button" Button { viewModel.add() } label: { Text("Enact bolus") }

/* Enact Bolus title */
"Enact Bolus Title" = "Enact Bolus Title"; <-- for the title of the view .navigationTitle("Enact Bolus Title") 

```
If you prefer, you could commit the PR and take the lead for the internationalization ;-)

2021-04-15 20:56 UTC, ivalkou commented
@avouspierre It should be like this:

"Key" = "Value";

```
"Enact bolus" = "Enact bolus";
"Enact Bolus Title" = "Enact Bolus";

"Add Carbs" = "Add Carbs";
"Add Carbs Title" = "Add Carbs";
```

The value is how it will look in the UI.

2021-04-17 14:14 UTC, avouspierre commented
@ivalkou Sorry, bug in my brain.. Correction done in the last version + integration of the last master version

2021-05-31 09:55 UTC, Jon-b-m commented
avouspierre, I think I can help. I created a crowding project with a public license for freeaps x. I'ts still empty, and perhaps it's a bit to soon to start translating, but anyway, perhaps we could use this project henceforth to organize the translations...

2021-09-19 16:44 UTC, ivalkou commented
https://github.com/ivalkou/freeaps/pull/83

2021-09-19 16:44 UTC, closed without merging